# Generated by Django 5.2.1 on 2025-06-10 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_alter_product_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="size",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
