# Generated by Django 5.2.1 on 2025-06-10 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_custom_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='custom_id',
            field=models.CharField(default='TEMP', max_length=10, unique=True),
        ),
    ]
