# Generated by Django 5.2.1 on 2025-06-11 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_custom_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='custom_id',
        ),
    ]
