# Generated by Django 5.2.1 on 2025-08-29 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0009_product_sku"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="extra_information",
            field=models.TextField(blank=True, null=True),
        ),
    ]
